import pyautogui
print(pyautogui.position())
pyautogui.moveTo(831,1059)
pyautogui.click()
pyautogui.moveTo(1424,17)
pyautogui.click()
pyautogui.moveTo(707,62)
pyautogui.click()
pyautogui.write('hfpevty kb z?')
pyautogui.press('enter')